# Generated by Django 5.0.4 on 2024-04-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('mobile', models.CharField(max_length=20)),
                ('feedback', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Loan_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('married', models.IntegerField()),
                ('dependents', models.IntegerField()),
                ('education', models.IntegerField()),
                ('self_employed', models.IntegerField()),
                ('applicantIncome', models.FloatField()),
                ('coapplicantIncome', models.IntegerField()),
                ('loan_amount_term', models.IntegerField()),
                ('credit_history', models.IntegerField()),
                ('property_area', models.IntegerField()),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
