# Generated by Django 5.0.4 on 2024-04-06 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan_data',
            name='loan_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='applicantIncome',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='coapplicantIncome',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='credit_history',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='loan_data',
            name='loan_amount_term',
            field=models.FloatField(),
        ),
    ]
